version: '3'

services:
  ansible:
    build:
      ./ansible
    volumes:
      - ~/Desktop/DevOps-Ansible/ansible-docker:/home/ansible/Automation
      - ~/.ssh:/home/ansible/.ssh
      - ~/.gitconfig:/home/ansible/.gitconfig
    stdin_open: true
    tty: true
    command: tail -f /dev/null
  # jenkins:
  #   image: jenkins-ansible
  #   environment:
  #     JAVA_OPTS: -Djenkins.install.runSetupWizard=false
  #     JENKINS_OPTS: --argumentsRealm.roles.user=admin --argumentsRealm.passwd.admin=admin --argumentsRealm.roles.admin=admin
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - /var/run.docker.sock:/var/run/docker.sock
  #   build:
  #     context: ./jenkins-docker