---
- name: "Check if certificate exists"
  stat:
    path: "{{jenkins_etc_directory}}/{{jenkins_keystore_file}}"
  register: chk_cert_file

- set_fact:
    jenkins_certificate_file: "{% if chk_cert_file.stat.exists == true %}present{%else%}absent{%endif%}"