---
- name: "Extract certificate from Keystore"
  shell: |
    openssl pkcs12 -in {{jenkins_etc_directory}}/{{jenkins_keystore_file}} -out {{temp_folder.path}}/cert.pem \
     -password pass:{{jenkins_certificates|json_query(jq_cert_keystore_password)}} \
     -passout pass:{{jenkins_certificates|json_query(jq_cert_keystore_password)}}

- name: "Save certificate"
  copy:
    content: "{{jenkins_certificates|json_query(jq_cert_cert)}}"
    dest: "{{temp_folder.path}}/{{jenkins_cert_cert_name}}"

- name: "Get current certificate fingerprint"
  shell: |
    openssl x509 -noout -fingerprint -sha256 -inform pem -in {{temp_folder.path}}/cert.pem|awk -F'=' '{print $2}'
  register: chk_current_cert


- name: "Get required certificate fingerprint"
  shell: |
    openssl x509 -noout -fingerprint -sha256 -inform pem -in {{temp_folder.path}}/{{jenkins_cert_cert_name}}|awk -F'=' '{print $2}'
  register: chk_required_cert

- set_fact:
    jenkins_cert_changed: "{% if chk_required_cert.stdout != chk_current_cert.stdout %}true{%else%}false{%endif%}"

