---
- name: "Save certificate"
  copy:
    content: "{{jenkins_certificates|json_query(jq_cert_cert)}}"
    dest: "{{temp_folder.path}}/{{jenkins_cert_cert_name}}"


- debug:
    msg: "validity period : {{jenkins_seconds_expiration_notification}}"

#Take the expiration date, convert it to UNIX time and add 10 days and check if this is bigger than the current date
- name: "Get current certificate expiration date"
  shell: |
    [[ $(date -d"$(openssl x509 -noout -in {{temp_folder.path}}/{{jenkins_cert_cert_name}} -dates|grep ^notAfter|awk -F'=' '{print $2}')" +%s) -lt $(expr $(date +%s) + {{jenkins_seconds_expiration_notification}}) ]] && echo "EXPIRED" || echo "OK"
  register: chk_current_expi

- set_fact:
    jenkins_cert_expired: "{% if chk_current_expi.stdout != 'OK' %}true{%else%}false{%endif%}"