---
#Check if certificate is already configured in Jenkins
#Take the file configuration and check if the keystore is configured
- name: "Check if certificate is configured"
  shell: |
     grep -q '^JENKINS_HTTPS_KEYSTORE="{{jenkins_etc_directory}}/{{jenkins_keystore_file}}"$' {{jenkins_etc_directory}}/sysconfig/jenkins && echo OK || echo KO
  register: chk_cert_syslog

- set_fact:
    jenkins_certificate_configured: "{%if chk_cert_syslog.stdout == 'OK' %}true{%else%}false{%endif%}"