---
#Save certificate value to file

- name: "Save certificate"
  copy:
    content: "{{jenkins_certificates|json_query(jq_cert_cert)}}"
    dest: "{{temp_folder.path}}/{{jenkins_cert_cert_name}}"

#Save key value to file
- name: "Save certificate"
  copy:
    content: "{{jenkins_certificates|json_query(jq_cert_key)}}"
    dest: "{{temp_folder.path}}/{{jenkins_cert_key_name}}"

##openssl pkcs12 -export -out ip-10-20-238-222.pfx -inkey ip-10-20-238-222.key -in ip-10-20-238-222.crt -password pass:hello123
- name: "Convert certificate and key to PKCS12 keystore"
  shell: |
    openssl pkcs12 -export -out {{jenkins_etc_directory}}/{{jenkins_keystore_file}} -inkey {{temp_folder.path}}/{{jenkins_cert_key_name}} \
        -in {{temp_folder.path}}/{{jenkins_cert_cert_name}} -password pass:{{jenkins_certificates|json_query(jq_cert_keystore_password)}}
#keytool -importkeystore -srckeystore ip-10-20-238-222.pfx -srcstoretype pkcs12 -destkeystore ip-10-20-238-222.jks -deststoretype JKS


- import_role:
    name: jenkins_cycle
  vars:
    jenkins_set_restart_flag: "yes"

#- name: "Generate final keystore"
#  shell: |
#    keytool -importkeystore -srcalias 1 -srckeystore {{temp_folder.path}}/{{jenkins_cert_pfx_name}} -srcstoretype pkcs12 \
#    -destkeystore {{jenkins_etc_directory}}/{{jenkins_keystore_file}} -destalias jenkins -deststoretype pkcs12 \
#    -srcstorepass {{jenkins_certificates|json_query(jq_cert_keystore_password)}} \
#    -deststorepass {{jenkins_certificates|json_query(jq_cert_keystore_password)}}