---
#Input:
#   ENV_SERVER_RESTART=yes
#Install or Update plugin
- include_vars: "roles/jenkins_update/vars/update_plugin.yml"

- name: "Download Jenkins CLI"
  get_url:
    url: "{{jenkins_cli_url}}"
    dest: "{{jenkins_home_directory}}/{{jenkins_cli_jar}}"

- name: "Check if plugin {{item.name}} is installed"
  shell: |
    {{jenkins_cli_cde}} list-plugins {{item.name}}
  ignore_errors: True
  register: chk_plugins
  with_items:
    - "{{jenkins_plugins}}"

- name: "Update or install {{item.name}}"
  shell: |
    {{jenkins_cli_cde}} install-plugin {{item.name}} {{jenkins_cli_opts}}
  with_items:
    - "{{chk_plugins|json_query(jq_plugin_installed)}}"
  register: do_install_plugin

- name: "Set restart required when new plugin has been installed"
  import_role:
    name: jenkins_cycle
  vars:
    jenkins_set_restart_flag: "yes"
  when: do_install_plugin is defined and do_install_plugin.results is defined and do_install_plugin.results[0] is defined